pipeline {   
    agent {
            kubernetes {
                label "pod-template-${UUID.randomUUID().toString()}"
                containers: [
                    containerTemplate {
                        name 'owasp-zap'
                        image 'https://hub.docker.com/r/owasp/zap2docker-stable'
                        ttyEnabled true
                }
            }
        }
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }

    }
}
